# Generated by Django 2.1.2 on 2018-11-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('whatsapp', models.IntegerField(max_length=15)),
                ('paytm', models.IntegerField(max_length=15)),
                ('pubg_uid', models.IntegerField(max_length=30)),
                ('pubg_uname', models.CharField(max_length=50)),
            ],
        ),
    ]
